#! /bin/bash

function office {
    # xrandr --output DP1 --auto --left-of DP2 --output DP2 --auto --output eDP1 --auto --pos 0x560 --primary --left-of DP1
    xrandr --output eDP1 --auto --pos 0x0 --output DP1 --auto --pos 2560x0 --primary --output DP2 --auto --right-of DP1
}

function home {
    xrandr --output DP-0 --auto --left-of DP-2 --output DP-2 --auto --primary --output DP-4 --auto --right-of DP-2 --output HDMI-0 --off
}

function isHome {
    xrandr | grep DP-4
}

if isHome
then
    home
else
    office
fi
